### ISSUE TITLE
define a anonymous interface will be error

### ISSUE THREAD

**Issue by myfjdthink** [tgreyuk/apidoc-plugin-ts#14]
if I define a anonymous interface like that:

```typescript
export interface Players {
  players: Array<{
    amount: number
    name: string,
  }>;
}

```

it will be get error

```bash
TypeError: prop.getType is not a function
    at setObjectElements (src/index.ts:150:8)
    at src/index.ts:167:9
    at Array.forEach (<anonymous>)
    at setObjectElements (src/index.ts:150:34)
    at src/index.ts:136:9
    at Array.forEach (<anonymous>)
    at setInterfaceElements (src/index.ts:101:36)
    at Object.parseElements (src/index.ts:47:7)
    at Context.<anonymous> (test/test.ts:19:5)
```

ast can't find a anonymous interface

![image](https://user-images.githubusercontent.com/2044143/48187333-c1fc0d00-e375-11e8-8509-4da7e5296b98.png)

**Comment by myfjdthink** [comment]
import other interface has same problem

```typescript
import {IBanner} from './base/IBanner'

export interface IProductList {
  banners: Array<IBanner>
}

```
